[project]
name = "01-chat-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.132.0",
    "openai>=2.23.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.41.0",
]
